# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XiaoShuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('caption', models.TextField()),
                ('detail', models.TextField()),
            ],
        ),
    ]
